transcript on
if {[file exists rtl_work]} {
	vdel -lib rtl_work -all
}
vlib rtl_work
vmap work rtl_work

vlib lab62_soc
vmap lab62_soc lab62_soc
vlog -vlog01compat -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/lab62_soc.v}
vlog -vlog01compat -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/altera_reset_controller.v}
vlog -vlog01compat -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/altera_reset_synchronizer.v}
vlog -vlog01compat -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/lab62_soc_mm_interconnect_0.v}
vlog -vlog01compat -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/lab62_soc_mm_interconnect_0_avalon_st_adapter_005.v}
vlog -vlog01compat -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/lab62_soc_mm_interconnect_0_avalon_st_adapter.v}
vlog -vlog01compat -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/altera_avalon_sc_fifo.v}
vlog -vlog01compat -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/lab62_soc_usb_rst.v}
vlog -vlog01compat -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/lab62_soc_usb_gpx.v}
vlog -vlog01compat -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/lab62_soc_timer_0.v}
vlog -vlog01compat -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/lab62_soc_sysid_qsys_0.v}
vlog -vlog01compat -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/lab62_soc_spi_0.v}
vlog -vlog01compat -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/lab62_soc_sdram_pll.v}
vlog -vlog01compat -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/lab62_soc_sdram.v}
vlog -vlog01compat -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/lab62_soc_onchip_memory2_0.v}
vlog -vlog01compat -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/lab62_soc_nios2_qsys_0.v}
vlog -vlog01compat -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/lab62_soc_nios2_qsys_0_jtag_debug_module_sysclk.v}
vlog -vlog01compat -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/lab62_soc_nios2_qsys_0_jtag_debug_module_tck.v}
vlog -vlog01compat -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/lab62_soc_nios2_qsys_0_jtag_debug_module_wrapper.v}
vlog -vlog01compat -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/lab62_soc_nios2_qsys_0_oci_test_bench.v}
vlog -vlog01compat -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/lab62_soc_nios2_qsys_0_test_bench.v}
vlog -vlog01compat -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/lab62_soc_leds_pio.v}
vlog -vlog01compat -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/lab62_soc_keycode.v}
vlog -vlog01compat -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/lab62_soc_key.v}
vlog -vlog01compat -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/lab62_soc_jtag_uart_0.v}
vlog -vlog01compat -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/lab62_soc_hex_digits_pio.v}
vlog -vlog01compat -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/lab62_soc_acc.v}
vlog -sv -work work +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6 {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/GameStateController.sv}
vlog -sv -work work +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6 {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/walldecider.sv}
vlog -sv -work work +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6 {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/HexDriver.sv}
vlog -sv -work work +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6 {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/Color_Mapper.sv}
vlog -sv -work work +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6 {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/ball.sv}
vlog -sv -work work +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6 {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/VGA_controller.sv}
vlog -sv -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/lab62_soc_irq_mapper.sv}
vlog -sv -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/lab62_soc_mm_interconnect_0_avalon_st_adapter_005_error_adapter_0.sv}
vlog -sv -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/lab62_soc_mm_interconnect_0_avalon_st_adapter_error_adapter_0.sv}
vlog -vlog01compat -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/altera_avalon_st_handshake_clock_crosser.v}
vlog -vlog01compat -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/altera_avalon_st_clock_crosser.v}
vlog -vlog01compat -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/altera_std_synchronizer_nocut.v}
vlog -sv -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/altera_merlin_width_adapter.sv}
vlog -sv -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/altera_merlin_burst_uncompressor.sv}
vlog -sv -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/lab62_soc_mm_interconnect_0_rsp_mux.sv}
vlog -sv -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/altera_merlin_arbitrator.sv}
vlog -sv -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/lab62_soc_mm_interconnect_0_rsp_demux.sv}
vlog -sv -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/lab62_soc_mm_interconnect_0_cmd_mux.sv}
vlog -sv -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/lab62_soc_mm_interconnect_0_cmd_demux.sv}
vlog -sv -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/altera_merlin_burst_adapter.sv}
vlog -sv -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/altera_merlin_burst_adapter_uncmpr.sv}
vlog -sv -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/lab62_soc_mm_interconnect_0_router_007.sv}
vlog -sv -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/lab62_soc_mm_interconnect_0_router_002.sv}
vlog -sv -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/lab62_soc_mm_interconnect_0_router.sv}
vlog -sv -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/altera_merlin_slave_agent.sv}
vlog -sv -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/altera_merlin_master_agent.sv}
vlog -sv -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/altera_merlin_slave_translator.sv}
vlog -sv -work lab62_soc +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62_soc/synthesis/submodules/altera_merlin_master_translator.sv}
vlog -sv -work work +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6 {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/lab62.sv}

vlog -sv -work work +incdir+C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6 {C:/Users/rushi/Desktop/tthakur2_rushill2_lab6/tthakur2_rushill2_lab6/testbench.sv}

vsim -t 1ps -L altera_ver -L lpm_ver -L sgate_ver -L altera_mf_ver -L altera_lnsim_ver -L fiftyfivenm_ver -L rtl_work -L work -L lab62_soc -voptargs="+acc"  testbench

add wave *
view structure
view signals
run 2000 ns
